version: '3.7'

services:
  book_friend_api:
    container_name: book_friend_server
    build: ./
    working_dir: /usr/src/book_friend_server
    volumes: 
      - ./:/usr/src/book_friend_server
    environment:
      POSTGRES_URI: postgres://francois:secret@postgres:5432/book-friend-api-docker
      REDIS_URI: redis://redis:6379
    ports:
      - "3000:3000"
    command: npm start
  postgres:
    build: ./postgres
    environment:
      POSTGRES_USER: francois
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: book-friend-api-docker
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"