version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3 
    steps:
      - checkout
      - run: echo "installing and start"
      - run: npm install
      - run: docker-compose up --build
workflows:
  version: 2
  build:
    jobs:
      - build